name: CUDA & OpenGL Build Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-cuda:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
       submodules: true

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: false
        dotnet: true
        haskell: true
        large-packages: false
        swap-storage: true

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1-mesa-dev libx11-dev libxrandr-dev libxinerama-dev \
          libxcursor-dev libxi-dev ninja-build
          
    - name: Install compatible GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
    
    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.20
      with:
        cuda: '12.2.0'
        method: 'local'
        use-github-cache: 'true'
        linux-local-args: '["--toolkit"]'

    - name: Restore vcpkg binary cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg-cuda-${{ hashFiles('vcpkg.json') }}

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_CUDA_ARCHITECTURES="61;75;86;89-real;89-virtual" \
          -G Ninja

    - name: Build
      run: cmake --build build --config Release

    - name: Prepare Release Package
      run: |
        mkdir release_paczka
        cp build/water release_paczka/
        cp -r shaders release_paczka/
        cp -r models release_paczka/
        cp config.txt release_paczka/
        tar -czvf water-sim-linux-cuda.tar.gz -C release_paczka .

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: water-sim-build-linux
        path: life-sim-linux-cuda.tar.gz
      
